name: test_action

on: [push, pull_request]

jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
   - name: checkout repo content
     uses: actions/checkout@v2
   - name: setup python
     uses: actions/setup-python@v2
     with:
       python-version: 3.7.6
   - name: run test script
     run: |
       pip install numpy==1.19.2
       pip install llvmlite==0.32.1
       pip install scipy==1.5.2
       pip install numba==0.49
       pip install pandas==1.1.3
       pip install matplotlib==3.3.2       
       pip install ipython==7.18.1
       python setup.py install
       python tests_golden/runAllTests.py
   - name: Archive code coverage results
     uses: actions/upload-artifact@v2
     with:
        name: result-differences-file-upload
        path: tests/differences/*.testLog

